modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="minecart_speed"
version="1.0.0"
displayName="Minecart Speed"
authors="Lawson_Hui"
description='''
Per-minecart speed control via commands.
'''

[[dependencies.minecart_speed]]
    modId="forge"
    mandatory=true
    versionRange="[65,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minecart_speed]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"
